Issue #30: Nutrient registration number
ai-cfia/fertiscan-pipeline pull request #33
Opened 2024-09-16 11:14 UTC by snakedye

Breaking Change:

- The quantity in the nutrient object is now in an object.
- `registration_number` field in the nutrient object.

> Nutrients and ingredients are treated the same way. 

Closes #30

2024-09-16 18:04 UTC, Francois-Werbrouck requested changes

2024-09-16 18:04 UTC, Francois-Werbrouck commented on expected.json
Can we keep the nutrient object as they were? 

```JSON
"nutrient": "Total Nitrogen (N)",
        "value": 20,
        "unit": "%"
        "value": 20,
        "unit": "%",
        "registration_number": "RN123"
      },
```

Unless it helps the models, this would require alot on unnecessary changes in the datastore.

2024-09-16 18:54 UTC, snakedye commented on expected.json
I changed it to make it more clear for the LLM but this change is too big I can keep the old structure and add a description.

2024-11-04 16:16 UTC, k-allagbe commented
Will be done in #73.

2024-11-04 16:16 UTC, closed without merging